### ISSUE TITLE
Incompatibility issue with the newest version of Goland (GO-222.3345.118)

### ISSUE THREAD

**Issue by Plenituz** [zzehring/intellij-jsonnet#14]
After updating to the latest version of Goland about a week or so ago, I've been getting the following error message:
```
Plugin 'Jsonnet Language Server' (version '0.0.7') is not compatible with the current version of the IDE, because it requires build 221.* or older but the current build is GO-222.3345.118
```
I also tried the install from disk method which yields the same result.

I think this might be fixed by updating the value to `222.*` here: 
https://github.com/zzehring/intellij-jsonnet/blob/2e9b9cd51729ccc8761deda623e44a9fcff24b49/gradle.properties#L12
but I'm not sure since I'm very unfamiliar with the whole plugin system

Thanks

**Comment by zzehring** [comment]
Thanks for logging this issue! I'll be submitting the new version soon, so hopefully will have the update available tomorrow.
