### ISSUE TITLE
Not binding libsonnet files

### ISSUE THREAD

**Issue by cm3brian** [zzehring/intellij-jsonnet#26]
Hello, 

Thanks for all the work on this and for jumping on my last report very quickly, much appreciated.

Can the plugin please be setup to bind also `*.libsonnet`/`.libsonnet` file types as well, I have to keep adding it each restart as for some reason the bindings are not persisted for me when manually added.

A fresh plugin install for me shows no bindings for the file types:
<img width="744" alt="image" src="https://user-images.githubusercontent.com/109269354/199365365-7610cd09-e5cf-486d-83f8-8bcd718450ed.png">

**Comment by zzehring** [comment]
Of course! Thanks for your suggestions on improving the tool.

> Can the plugin please be setup to bind also *.libsonnet/.libsonnet file types as well, I have to keep adding it each restart as for some reason the bindings are not persisted for me when manually added.

It should do that upon installation: https://github.com/zzehring/intellij-jsonnet/blob/9d26a3d451109f06e2aa08f1ac2fa612662ec0f3/src/main/resources/META-INF/plugin.xml#L50-L54

I do wonder if those extensions got associated with another file type. I did have to manually add one of them when running the plugin in GoLand for the first time during development. So it may be an issue with your IDE configuration. It's definitely strange that you have to _keep_ adding it to the `File name patterns`. Could there be an issue with your IDE install? I'd maybe see if you get the same results in another Jetbrains IDE to test.

**Comment by cm3brian** [comment]
I got this to persist with full reinstall so may have been specific to my install. Thanks.
