### ISSUE TITLE
IntelliJ Idea can't load project after installing plugin

### ISSUE THREAD

**Issue by niels-s** [zzehring/intellij-jsonnet#28]
I can't open any project anymore. The plugin crashes immediately after starting Intellij Idea.
I'm using v2022.2.3 and plugin 0.0.9

Is there a workaround? 
![CleanShot 2022-11-10 at 15 17 04](https://user-images.githubusercontent.com/1531951/201115365-dcb15a1d-7f62-4b78-b4f5-ec7462cb482f.png)

**Comment by zzehring** [comment]
Additionally, what platform/arch are you using?

**Comment by zzehring** [comment]
I found this issue that looks very close to the problem you're running into: https://gitlab.com/sharedvocabs/intellij-rdf-plugin/-/issues/45

The workaround for the above issue:

> The issue caused by a conflict with [LNKD.tech Editor](https://plugins.jetbrains.com/plugin/12802-lnkd-tech-editor) which also provides support for RDF Turtle language. The easy solution is to uninstall the LNKD plugin :smile:The issue caused by a conflict with [LNKD.tech Editor](https://plugins.jetbrains.com/plugin/12802-lnkd-tech-editor) which also provides support for RDF Turtle language. The easy solution is to uninstall the LNKD plugin 😄

Issue is a bit dated, but it doesn't look like it's been fixed: https://youtrack.jetbrains.com/issue/IDEA-236643

Do you have another Jsonnet plugin installed that could be conflicting with the Jsonnet file type?

**Comment by niels-s** [comment]
@zzehring, thanks for your help. I had indeed installed the Databricks jsonnet too, which probably caused the naming collision. After uninstalling that one the plugin worked like a charm👌 Sorry for the noise.
