### ISSUE TITLE
Add support for IDE versions 2023

### ISSUE THREAD

**Issue by cm3brian** [zzehring/intellij-jsonnet#49]
Current latest build version is `231.*` (2023.1)

Aware that last time out this triggered a bunch of work with minimum version upgrades, etc though.

ref: https://plugins.jetbrains.com/docs/intellij/build-number-ranges.html#intellij-platform-based-products-of-recent-ide-versions

**Comment by electron0zero** [comment]
Plugin fails on GoLand 2023.1 with following error: `Plugin 'Jsonnet Language Server' (version '0.1.1') is not compatible with the current version of the IDE, because it requires build 223.* or older but the current build is GO-231.8109.199`

**Comment by zzehring** [comment]
Closed by: https://github.com/zzehring/intellij-jsonnet/releases/tag/v0.1.2
