### ISSUE TITLE
Doesn't work in PyCharm 2022.1.2 Community Edition

### ISSUE THREAD

**Issue by oleg-glushak** [zzehring/intellij-jsonnet#7]
I've installed the plugin from [here](https://plugins.jetbrains.com/plugin/18752-jsonnet-language-server) (v0.0.5). The latest available jsonnet language server 0.7.2 has been successfully downloaded. On the status bar at the bottom of the window I see that the language server is running, but features like autocomplete, jump to definition and others do not work for both *.jsonnet and *.libsonnet files. The only thing that works is syntax highlighting. I also haven't noticed any errors.

Maybe I'm missing something obvious, not sure.

**Comment by zzehring** [comment]
Regarding autocomplete, the [language server](https://github.com/grafana/jsonnet-language-server) currently only supports autocomplete for [the stdlib](https://github.com/grafana/jsonnet-language-server#standard-library-hover-and-autocomplete). However, there are [several autocomplete issues](https://github.com/grafana/jsonnet-language-server/issues?q=is%3Aissue+is%3Aopen+Completion) on the roadmap.

For jump-to-definiton, how are you invoking the action? I tested this and found `^ + click` (`⌘ + click` for macOS) works but other methods (e.g. `^ + B`, Navigate->Declaration or Usages, via Right Click menu, etc) don't work and return an error popup with `Cannot find declaration to go to`. I'm thinking this may be a quirk with the [lsp4intellij](https://github.com/ballerina-platform/lsp4intellij) framework used by the plugin. They only mention the use of `^ + click` in their README for navigating to definition.

If `^ + click` doesn't work for you (or stdlib autocomplete isn't working), I'd be interested in your Timeouts view for the language server (green/red dot in bottom left):

![image](https://user-images.githubusercontent.com/7545035/173138963-9d516f49-bac1-43d1-b879-3ec520a19e5d.png)

**Comment by oleg-glushak** [comment]
I'm using MacOS and does indeed works with `⌘ + click`. That's great. This is functionality is already good enough to continue using the plugin.
Normally I use `⌘ + B` for the same functionality, so I was surprised that it doesn't work. None of the actions in the `Right Click menu` works as well. 

Thanks a lot! Even though it still doesn't work as I'm used to, it's enough for now to benefit from it. Closing the ticket, since the issue title doesn't seem to be correct.

**Comment by zzehring** [comment]
For posterity, the lack of other methods for "Go To Definition" is a known issue for the framework: https://github.com/ballerina-platform/lsp4intellij/issues/183 . If there's a need, I could look into resolving that issue upstream.
